CREATE TABLE `items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `channel` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `property_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location_title` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active` tinyint unsigned NOT NULL DEFAULT '0',
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price_min` decimal(12,2) NOT NULL DEFAULT '0.00',
  `price_max` decimal(12,2) NOT NULL DEFAULT '0.00',
  `organisation_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `organisation_name` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `organisation_phone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `organisation_mobile` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `organisation_whatsapp` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `organisation_email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lister_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lister_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lister_license` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lister_phone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lister_mobile` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lister_whatsapp` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lister_email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `keyword` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tab` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq` (`property_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;